version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: invest
      POSTGRES_PASSWORD: investpw
      POSTGRES_DB: investdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  

  redis:
    image: redis:7
    ports:
      - "6379:6379"  

  backend:
    build: ./backend
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://invest:investpw@db:5432/investdb
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000" 
    volumes:
      - ./backend:/app 
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  db_data: